### ISSUE TITLE
error: division by zero

### ISSUE THREAD

**Issue by abczefg** [12rambau/restoration_planning_module#101]
I was trying this recipe (attached) and the COMPUTE DASHBOARD step it returns this error: division by zero.
[recipe_2021-12-20.txt](https://github.com/12rambau/restoration_planning_module/files/7742354/recipe_2021-12-20.txt)

**Comment by jdilger** [comment]
Hi @abczefg, there seems to be a bug in the land cover constraints that is causing this issue. We are working to locate the exact cause of the error. In the meantime, if you remove the land constraints you should be able to compute the dashboard.

**Comment by jdilger** [comment]
@12rambau Not sure if you have had a moment to look into this at all, but it's a strange issue. I think the issue is occurring somewhere when the WLC is calculated. The WLC image is shown, but if you use the inspector all the returned values are None. On test cases without using land cover constraints it returns the expected values.

**Comment by 12rambau** [comment]
I'm just coming back from holidays and I need a refresher on this one. I assume that the constraint is then odly computed and every pixels are masked. I'll check the constraint builder

**Comment by jdilger** [comment]
@12rambau Just to follow up on this I think I pinpointed where the error is happening. It seems to happen during the expression portion when each constraint is multiplied. In one test case, I found the issue happened when the landcover class was multiplied against the baseline restoration layer. My best guess is that the masks on each image are causing the issue since they're all in the same projection and pixelType and unmasking resulted in the expected behaviour. 

Unmasking them all before the calculation should solve the issue, but I will need to see if it causes any other issues.

**Comment by 12rambau** [comment]
Nice intuition indeed. The mask from the Land classification was ending up blocking the expression because masked * masked is not a supported operation for GEE....

What I did is simply unmask the map before running the `neq`/`eq` operation.

As the global mask is provided by the treecover_with_potential layer it doesn't matter if some water bodies are included in the computation at this stage.
