### ISSUE TITLE
Release version broken?

### ISSUE THREAD

**Issue by jdilger** [12rambau/restoration_planning_module#57]
Is the release version of se.plan working for you @12rambau ? When I try to run it in SEPAL I get an error on cell 5.

`There was an error when executing cell [5]. Please run Voilà with --show_tracebacks=True or --debug to see the error message, or configure VoilaConfiguration.show_tracebacks.`

**Comment by jdilger** [comment]
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-e73cb725735b> in <module>
      4     appBar=rp_appBar,
      5     navDrawer=rp_drawer
----> 6 ).show_tile('about_tile')

~/.local/lib/python3.6/site-packages/sepal_ui/sepalwidgets/app.py in show_tile(self, name)
    333             if self.navDrawer:
    334                 for i in self.navDrawer.items:
--> 335                     if name == i._metadata['card_id']:
    336                         i.input_value = True
    337 

TypeError: 'NoneType' object is not subscriptable
```

**Comment by 12rambau** [comment]
On my side it's working, considering the bug you're showing it's coming from the sepal_ui implementation that you are working with. Can you please run `pip freeze | grep sepal-ui`and let me know what version of sepal_ui is currently installed in your SEPAL env ?

**Comment by jdilger** [comment]
Ah ok. I was using sepal-ui 2.0.3 and upgrading to 2.0.6 did the trick. Do I need to keep this package up to date?  For some reason, I thought you all handled that in the background.

**Comment by 12rambau** [comment]
> Do I need to keep this package up to date?

No we are effectively taking care of it for you in the background (and we are developping a venv manager for apps so that no user will continue to experience this type of bug). 

The problem is that you have installed in .local once and the local installation has priority over global. The way to go back to SEPAL factory settings is to uninstall it:
```
pip uninstall sepal-ui
```

As you don't have writting rights on `/usr/` only the local version will be deleted. if you check the version again after this operation, you should be back to 2.0.6.

**Comment by jdilger** [comment]
Very cool, thank you!
